<template>
    <aritcle>
        <header>
            <h2>
                Domitory
            </h2>
        </header>
        <body>
            <section>
                <div>
                    <h3>
                        Scholarship
                    </h3>
                </div>
                <div>
                    <h3>
                        Special Awards
                    </h3>
                </div>
            </section>
        </body>
    </aritcle>
</template>